apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: test-iua
  namespace: flux-system
spec:
  image: ghcr.io/matheuscscp/fluxcd/source-controller
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: my-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: test-iua
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: test-iua
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@my-instance.gitlab
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println
        .NewValue}}{{end}}'
    push:
      branch: main
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/staging/test-iua
    strategy: Setters
